/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MerchantHealthRouteImport } from './routes/merchant-health'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as AcademyMerchantRiskFundamentalsRouteImport } from './routes/academy/merchant-risk-fundamentals'
import { Route as TagsSlugRouteImport } from './routes/tags/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchantHealthRoute = MerchantHealthRouteImport.update({
  id: '/merchant-health',
  path: '/merchant-health',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyMerchantRiskFundamentalsRoute =
  AcademyMerchantRiskFundamentalsRouteImport.update({
    id: '/academy/merchant-risk-fundamentals',
    path: '/academy/merchant-risk-fundamentals',
    getParentRoute: () => rootRouteImport,
  } as any)
const TagsSlugRoute = TagsSlugRouteImport.update({
  id: '/tags/$slug',
  path: '/tags/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/merchant-health': typeof MerchantHealthRoute
  '/resources': typeof ResourcesRoute
  '/academy/merchant-risk-fundamentals': typeof AcademyMerchantRiskFundamentalsRoute
  '/tags/$slug': typeof TagsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/merchant-health': typeof MerchantHealthRoute
  '/resources': typeof ResourcesRoute
  '/academy/merchant-risk-fundamentals': typeof AcademyMerchantRiskFundamentalsRoute
  '/tags/$slug': typeof TagsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/merchant-health': typeof MerchantHealthRoute
  '/resources': typeof ResourcesRoute
  '/academy/merchant-risk-fundamentals': typeof AcademyMerchantRiskFundamentalsRoute
  '/tags/$slug': typeof TagsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/merchant-health'
    | '/resources'
    | '/academy/merchant-risk-fundamentals'
    | '/tags/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/merchant-health'
    | '/resources'
    | '/academy/merchant-risk-fundamentals'
    | '/tags/$slug'
  id:
    | '__root__'
    | '/'
    | '/merchant-health'
    | '/resources'
    | '/academy/merchant-risk-fundamentals'
    | '/tags/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MerchantHealthRoute: typeof MerchantHealthRoute
  ResourcesRoute: typeof ResourcesRoute
  AcademyMerchantRiskFundamentalsRoute: typeof AcademyMerchantRiskFundamentalsRoute
  TagsSlugRoute: typeof TagsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchant-health': {
      id: '/merchant-health'
      path: '/merchant-health'
      fullPath: '/merchant-health'
      preLoaderRoute: typeof MerchantHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/merchant-risk-fundamentals': {
      id: '/academy/merchant-risk-fundamentals'
      path: '/academy/merchant-risk-fundamentals'
      fullPath: '/academy/merchant-risk-fundamentals'
      preLoaderRoute: typeof AcademyMerchantRiskFundamentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tags/$slug': {
      id: '/tags/$slug'
      path: '/tags/$slug'
      fullPath: '/tags/$slug'
      preLoaderRoute: typeof TagsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MerchantHealthRoute: MerchantHealthRoute,
  ResourcesRoute: ResourcesRoute,
  AcademyMerchantRiskFundamentalsRoute: AcademyMerchantRiskFundamentalsRoute,
  TagsSlugRoute: TagsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
